#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MDK_DB")]
	public partial class MDKDBMLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBankInfo(BankInfo instance);
    partial void UpdateBankInfo(BankInfo instance);
    partial void DeleteBankInfo(BankInfo instance);
    partial void InsertUserMangement(UserMangement instance);
    partial void UpdateUserMangement(UserMangement instance);
    partial void DeleteUserMangement(UserMangement instance);
    partial void InsertRoleMangemant(RoleMangemant instance);
    partial void UpdateRoleMangemant(RoleMangemant instance);
    partial void DeleteRoleMangemant(RoleMangemant instance);
    partial void InsertPersonalInformation(PersonalInformation instance);
    partial void UpdatePersonalInformation(PersonalInformation instance);
    partial void DeletePersonalInformation(PersonalInformation instance);
    partial void InsertITInfo(ITInfo instance);
    partial void UpdateITInfo(ITInfo instance);
    partial void DeleteITInfo(ITInfo instance);
    partial void InsertOtherInfo(OtherInfo instance);
    partial void UpdateOtherInfo(OtherInfo instance);
    partial void DeleteOtherInfo(OtherInfo instance);
    #endregion
		
		public MDKDBMLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MDKDBMLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MDKDBMLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MDKDBMLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BankInfo> BankInfos
		{
			get
			{
				return this.GetTable<BankInfo>();
			}
		}
		
		public System.Data.Linq.Table<UserMangement> UserMangements
		{
			get
			{
				return this.GetTable<UserMangement>();
			}
		}
		
		public System.Data.Linq.Table<RoleMangemant> RoleMangemants
		{
			get
			{
				return this.GetTable<RoleMangemant>();
			}
		}
		
		public System.Data.Linq.Table<PersonalInformation> PersonalInformations
		{
			get
			{
				return this.GetTable<PersonalInformation>();
			}
		}
		
		public System.Data.Linq.Table<ITInfo> ITInfos
		{
			get
			{
				return this.GetTable<ITInfo>();
			}
		}
		
		public System.Data.Linq.Table<OtherInfo> OtherInfos
		{
			get
			{
				return this.GetTable<OtherInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BankInfo")]
	public partial class BankInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _BankName;
		
		private string _Branch;
		
		private string _AccountNo;
		
		private string _IFSC_CODE;
		
		private string _MICR_CODE;
		
		private string _BANK_ADDRESS;
		
		private string _BANK_CONTACT_NO;
		
		private string _BusinessGUID;
		
		private EntityRef<PersonalInformation> _PersonalInformation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBranchChanging(string value);
    partial void OnBranchChanged();
    partial void OnAccountNoChanging(string value);
    partial void OnAccountNoChanged();
    partial void OnIFSC_CODEChanging(string value);
    partial void OnIFSC_CODEChanged();
    partial void OnMICR_CODEChanging(string value);
    partial void OnMICR_CODEChanged();
    partial void OnBANK_ADDRESSChanging(string value);
    partial void OnBANK_ADDRESSChanged();
    partial void OnBANK_CONTACT_NOChanging(string value);
    partial void OnBANK_CONTACT_NOChanged();
    partial void OnBusinessGUIDChanging(string value);
    partial void OnBusinessGUIDChanged();
    #endregion
		
		public BankInfo()
		{
			this._PersonalInformation = default(EntityRef<PersonalInformation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(200)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="NVarChar(200)")]
		public string Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this.OnBranchChanging(value);
					this.SendPropertyChanging();
					this._Branch = value;
					this.SendPropertyChanged("Branch");
					this.OnBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo", DbType="NVarChar(50)")]
		public string AccountNo
		{
			get
			{
				return this._AccountNo;
			}
			set
			{
				if ((this._AccountNo != value))
				{
					this.OnAccountNoChanging(value);
					this.SendPropertyChanging();
					this._AccountNo = value;
					this.SendPropertyChanged("AccountNo");
					this.OnAccountNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFSC_CODE", DbType="NVarChar(50)")]
		public string IFSC_CODE
		{
			get
			{
				return this._IFSC_CODE;
			}
			set
			{
				if ((this._IFSC_CODE != value))
				{
					this.OnIFSC_CODEChanging(value);
					this.SendPropertyChanging();
					this._IFSC_CODE = value;
					this.SendPropertyChanged("IFSC_CODE");
					this.OnIFSC_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MICR_CODE", DbType="NVarChar(50)")]
		public string MICR_CODE
		{
			get
			{
				return this._MICR_CODE;
			}
			set
			{
				if ((this._MICR_CODE != value))
				{
					this.OnMICR_CODEChanging(value);
					this.SendPropertyChanging();
					this._MICR_CODE = value;
					this.SendPropertyChanged("MICR_CODE");
					this.OnMICR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANK_ADDRESS", DbType="NVarChar(500)")]
		public string BANK_ADDRESS
		{
			get
			{
				return this._BANK_ADDRESS;
			}
			set
			{
				if ((this._BANK_ADDRESS != value))
				{
					this.OnBANK_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._BANK_ADDRESS = value;
					this.SendPropertyChanged("BANK_ADDRESS");
					this.OnBANK_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANK_CONTACT_NO", DbType="NVarChar(100)")]
		public string BANK_CONTACT_NO
		{
			get
			{
				return this._BANK_CONTACT_NO;
			}
			set
			{
				if ((this._BANK_CONTACT_NO != value))
				{
					this.OnBANK_CONTACT_NOChanging(value);
					this.SendPropertyChanging();
					this._BANK_CONTACT_NO = value;
					this.SendPropertyChanged("BANK_CONTACT_NO");
					this.OnBANK_CONTACT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BusinessGUID
		{
			get
			{
				return this._BusinessGUID;
			}
			set
			{
				if ((this._BusinessGUID != value))
				{
					if (this._PersonalInformation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBusinessGUIDChanging(value);
					this.SendPropertyChanging();
					this._BusinessGUID = value;
					this.SendPropertyChanged("BusinessGUID");
					this.OnBusinessGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonalInformation_BankInfo", Storage="_PersonalInformation", ThisKey="BusinessGUID", OtherKey="BusinessGUID", IsForeignKey=true)]
		public PersonalInformation PersonalInformation
		{
			get
			{
				return this._PersonalInformation.Entity;
			}
			set
			{
				PersonalInformation previousValue = this._PersonalInformation.Entity;
				if (((previousValue != value) 
							|| (this._PersonalInformation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PersonalInformation.Entity = null;
						previousValue.BankInfos.Remove(this);
					}
					this._PersonalInformation.Entity = value;
					if ((value != null))
					{
						value.BankInfos.Add(this);
						this._BusinessGUID = value.BusinessGUID;
					}
					else
					{
						this._BusinessGUID = default(string);
					}
					this.SendPropertyChanged("PersonalInformation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserMangement")]
	public partial class UserMangement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Uid;
		
		private string _Role;
		
		private string _LoginName;
		
		private string _Password;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUidChanging(int value);
    partial void OnUidChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public UserMangement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Uid
		{
			get
			{
				return this._Uid;
			}
			set
			{
				if ((this._Uid != value))
				{
					this.OnUidChanging(value);
					this.SendPropertyChanging();
					this._Uid = value;
					this.SendPropertyChanged("Uid");
					this.OnUidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(20)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="NVarChar(200)")]
		public string LoginName
		{
			get
			{
				return this._LoginName;
			}
			set
			{
				if ((this._LoginName != value))
				{
					this.OnLoginNameChanging(value);
					this.SendPropertyChanging();
					this._LoginName = value;
					this.SendPropertyChanged("LoginName");
					this.OnLoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoleMangemant")]
	public partial class RoleMangemant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Rid;
		
		private string _RoleName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRidChanging(int value);
    partial void OnRidChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public RoleMangemant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Rid
		{
			get
			{
				return this._Rid;
			}
			set
			{
				if ((this._Rid != value))
				{
					this.OnRidChanging(value);
					this.SendPropertyChanging();
					this._Rid = value;
					this.SendPropertyChanged("Rid");
					this.OnRidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(50)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonalInformation")]
	public partial class PersonalInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pid;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _Address;
		
		private string _ContactNo;
		
		private string _AlternateNo;
		
		private string _EmailID;
		
		private string _DateOfBirth;
		
		private string _BusinessName;
		
		private string _BusinessType;
		
		private string _BusinessGUID;
		
		private EntitySet<BankInfo> _BankInfos;
		
		private EntitySet<ITInfo> _ITInfos;
		
		private EntitySet<OtherInfo> _OtherInfos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnAlternateNoChanging(string value);
    partial void OnAlternateNoChanged();
    partial void OnEmailIDChanging(string value);
    partial void OnEmailIDChanged();
    partial void OnDateOfBirthChanging(string value);
    partial void OnDateOfBirthChanged();
    partial void OnBusinessNameChanging(string value);
    partial void OnBusinessNameChanged();
    partial void OnBusinessTypeChanging(string value);
    partial void OnBusinessTypeChanged();
    partial void OnBusinessGUIDChanging(string value);
    partial void OnBusinessGUIDChanged();
    #endregion
		
		public PersonalInformation()
		{
			this._BankInfos = new EntitySet<BankInfo>(new Action<BankInfo>(this.attach_BankInfos), new Action<BankInfo>(this.detach_BankInfos));
			this._ITInfos = new EntitySet<ITInfo>(new Action<ITInfo>(this.attach_ITInfos), new Action<ITInfo>(this.detach_ITInfos));
			this._OtherInfos = new EntitySet<OtherInfo>(new Action<OtherInfo>(this.attach_OtherInfos), new Action<OtherInfo>(this.detach_OtherInfos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(1000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="NVarChar(20)")]
		public string ContactNo
		{
			get
			{
				return this._ContactNo;
			}
			set
			{
				if ((this._ContactNo != value))
				{
					this.OnContactNoChanging(value);
					this.SendPropertyChanging();
					this._ContactNo = value;
					this.SendPropertyChanged("ContactNo");
					this.OnContactNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternateNo", DbType="NVarChar(20)")]
		public string AlternateNo
		{
			get
			{
				return this._AlternateNo;
			}
			set
			{
				if ((this._AlternateNo != value))
				{
					this.OnAlternateNoChanging(value);
					this.SendPropertyChanging();
					this._AlternateNo = value;
					this.SendPropertyChanged("AlternateNo");
					this.OnAlternateNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailID", DbType="NVarChar(200)")]
		public string EmailID
		{
			get
			{
				return this._EmailID;
			}
			set
			{
				if ((this._EmailID != value))
				{
					this.OnEmailIDChanging(value);
					this.SendPropertyChanging();
					this._EmailID = value;
					this.SendPropertyChanged("EmailID");
					this.OnEmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="NVarChar(100)")]
		public string DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessName", DbType="NVarChar(100)")]
		public string BusinessName
		{
			get
			{
				return this._BusinessName;
			}
			set
			{
				if ((this._BusinessName != value))
				{
					this.OnBusinessNameChanging(value);
					this.SendPropertyChanging();
					this._BusinessName = value;
					this.SendPropertyChanged("BusinessName");
					this.OnBusinessNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessType", DbType="NVarChar(20)")]
		public string BusinessType
		{
			get
			{
				return this._BusinessType;
			}
			set
			{
				if ((this._BusinessType != value))
				{
					this.OnBusinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BusinessType = value;
					this.SendPropertyChanged("BusinessType");
					this.OnBusinessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BusinessGUID
		{
			get
			{
				return this._BusinessGUID;
			}
			set
			{
				if ((this._BusinessGUID != value))
				{
					this.OnBusinessGUIDChanging(value);
					this.SendPropertyChanging();
					this._BusinessGUID = value;
					this.SendPropertyChanged("BusinessGUID");
					this.OnBusinessGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonalInformation_BankInfo", Storage="_BankInfos", ThisKey="BusinessGUID", OtherKey="BusinessGUID")]
		public EntitySet<BankInfo> BankInfos
		{
			get
			{
				return this._BankInfos;
			}
			set
			{
				this._BankInfos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonalInformation_ITInfo", Storage="_ITInfos", ThisKey="BusinessGUID", OtherKey="BusinessGUID")]
		public EntitySet<ITInfo> ITInfos
		{
			get
			{
				return this._ITInfos;
			}
			set
			{
				this._ITInfos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonalInformation_OtherInfo", Storage="_OtherInfos", ThisKey="BusinessGUID", OtherKey="BusinessGUID")]
		public EntitySet<OtherInfo> OtherInfos
		{
			get
			{
				return this._OtherInfos;
			}
			set
			{
				this._OtherInfos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BankInfos(BankInfo entity)
		{
			this.SendPropertyChanging();
			entity.PersonalInformation = this;
		}
		
		private void detach_BankInfos(BankInfo entity)
		{
			this.SendPropertyChanging();
			entity.PersonalInformation = null;
		}
		
		private void attach_ITInfos(ITInfo entity)
		{
			this.SendPropertyChanging();
			entity.PersonalInformation = this;
		}
		
		private void detach_ITInfos(ITInfo entity)
		{
			this.SendPropertyChanging();
			entity.PersonalInformation = null;
		}
		
		private void attach_OtherInfos(OtherInfo entity)
		{
			this.SendPropertyChanging();
			entity.PersonalInformation = this;
		}
		
		private void detach_OtherInfos(OtherInfo entity)
		{
			this.SendPropertyChanging();
			entity.PersonalInformation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ITInfo")]
	public partial class ITInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pid;
		
		private string _IncomeTax;
		
		private string _PAN_NO;
		
		private string _TAN_NO;
		
		private string _VAT_NO;
		
		private string _CST_NO;
		
		private string _PTRC_NO;
		
		private string _PTEC_NO;
		
		private string _SalesTax;
		
		private string _BusinessGUID;
		
		private EntityRef<PersonalInformation> _PersonalInformation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnIncomeTaxChanging(string value);
    partial void OnIncomeTaxChanged();
    partial void OnPAN_NOChanging(string value);
    partial void OnPAN_NOChanged();
    partial void OnTAN_NOChanging(string value);
    partial void OnTAN_NOChanged();
    partial void OnVAT_NOChanging(string value);
    partial void OnVAT_NOChanged();
    partial void OnCST_NOChanging(string value);
    partial void OnCST_NOChanged();
    partial void OnPTRC_NOChanging(string value);
    partial void OnPTRC_NOChanged();
    partial void OnPTEC_NOChanging(string value);
    partial void OnPTEC_NOChanged();
    partial void OnSalesTaxChanging(string value);
    partial void OnSalesTaxChanged();
    partial void OnBusinessGUIDChanging(string value);
    partial void OnBusinessGUIDChanged();
    #endregion
		
		public ITInfo()
		{
			this._PersonalInformation = default(EntityRef<PersonalInformation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncomeTax", DbType="NVarChar(50)")]
		public string IncomeTax
		{
			get
			{
				return this._IncomeTax;
			}
			set
			{
				if ((this._IncomeTax != value))
				{
					this.OnIncomeTaxChanging(value);
					this.SendPropertyChanging();
					this._IncomeTax = value;
					this.SendPropertyChanged("IncomeTax");
					this.OnIncomeTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAN_NO", DbType="NVarChar(50)")]
		public string PAN_NO
		{
			get
			{
				return this._PAN_NO;
			}
			set
			{
				if ((this._PAN_NO != value))
				{
					this.OnPAN_NOChanging(value);
					this.SendPropertyChanging();
					this._PAN_NO = value;
					this.SendPropertyChanged("PAN_NO");
					this.OnPAN_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAN_NO", DbType="NVarChar(50)")]
		public string TAN_NO
		{
			get
			{
				return this._TAN_NO;
			}
			set
			{
				if ((this._TAN_NO != value))
				{
					this.OnTAN_NOChanging(value);
					this.SendPropertyChanging();
					this._TAN_NO = value;
					this.SendPropertyChanged("TAN_NO");
					this.OnTAN_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT_NO", DbType="NVarChar(50)")]
		public string VAT_NO
		{
			get
			{
				return this._VAT_NO;
			}
			set
			{
				if ((this._VAT_NO != value))
				{
					this.OnVAT_NOChanging(value);
					this.SendPropertyChanging();
					this._VAT_NO = value;
					this.SendPropertyChanged("VAT_NO");
					this.OnVAT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CST_NO", DbType="NVarChar(50)")]
		public string CST_NO
		{
			get
			{
				return this._CST_NO;
			}
			set
			{
				if ((this._CST_NO != value))
				{
					this.OnCST_NOChanging(value);
					this.SendPropertyChanging();
					this._CST_NO = value;
					this.SendPropertyChanged("CST_NO");
					this.OnCST_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTRC_NO", DbType="NVarChar(50)")]
		public string PTRC_NO
		{
			get
			{
				return this._PTRC_NO;
			}
			set
			{
				if ((this._PTRC_NO != value))
				{
					this.OnPTRC_NOChanging(value);
					this.SendPropertyChanging();
					this._PTRC_NO = value;
					this.SendPropertyChanged("PTRC_NO");
					this.OnPTRC_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTEC_NO", DbType="NVarChar(50)")]
		public string PTEC_NO
		{
			get
			{
				return this._PTEC_NO;
			}
			set
			{
				if ((this._PTEC_NO != value))
				{
					this.OnPTEC_NOChanging(value);
					this.SendPropertyChanging();
					this._PTEC_NO = value;
					this.SendPropertyChanged("PTEC_NO");
					this.OnPTEC_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesTax", DbType="NVarChar(50)")]
		public string SalesTax
		{
			get
			{
				return this._SalesTax;
			}
			set
			{
				if ((this._SalesTax != value))
				{
					this.OnSalesTaxChanging(value);
					this.SendPropertyChanging();
					this._SalesTax = value;
					this.SendPropertyChanged("SalesTax");
					this.OnSalesTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BusinessGUID
		{
			get
			{
				return this._BusinessGUID;
			}
			set
			{
				if ((this._BusinessGUID != value))
				{
					if (this._PersonalInformation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBusinessGUIDChanging(value);
					this.SendPropertyChanging();
					this._BusinessGUID = value;
					this.SendPropertyChanged("BusinessGUID");
					this.OnBusinessGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonalInformation_ITInfo", Storage="_PersonalInformation", ThisKey="BusinessGUID", OtherKey="BusinessGUID", IsForeignKey=true)]
		public PersonalInformation PersonalInformation
		{
			get
			{
				return this._PersonalInformation.Entity;
			}
			set
			{
				PersonalInformation previousValue = this._PersonalInformation.Entity;
				if (((previousValue != value) 
							|| (this._PersonalInformation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PersonalInformation.Entity = null;
						previousValue.ITInfos.Remove(this);
					}
					this._PersonalInformation.Entity = value;
					if ((value != null))
					{
						value.ITInfos.Add(this);
						this._BusinessGUID = value.BusinessGUID;
					}
					else
					{
						this._BusinessGUID = default(string);
					}
					this.SendPropertyChanged("PersonalInformation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OtherInfo")]
	public partial class OtherInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ServiceTaxNumber;
		
		private string _ExciseNumber;
		
		private string _PFESINumber;
		
		private string _BusinessGUID;
		
		private EntityRef<PersonalInformation> _PersonalInformation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnServiceTaxNumberChanging(string value);
    partial void OnServiceTaxNumberChanged();
    partial void OnExciseNumberChanging(string value);
    partial void OnExciseNumberChanged();
    partial void OnPFESINumberChanging(string value);
    partial void OnPFESINumberChanged();
    partial void OnBusinessGUIDChanging(string value);
    partial void OnBusinessGUIDChanged();
    #endregion
		
		public OtherInfo()
		{
			this._PersonalInformation = default(EntityRef<PersonalInformation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTaxNumber", DbType="NVarChar(50)")]
		public string ServiceTaxNumber
		{
			get
			{
				return this._ServiceTaxNumber;
			}
			set
			{
				if ((this._ServiceTaxNumber != value))
				{
					this.OnServiceTaxNumberChanging(value);
					this.SendPropertyChanging();
					this._ServiceTaxNumber = value;
					this.SendPropertyChanged("ServiceTaxNumber");
					this.OnServiceTaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExciseNumber", DbType="NVarChar(200)")]
		public string ExciseNumber
		{
			get
			{
				return this._ExciseNumber;
			}
			set
			{
				if ((this._ExciseNumber != value))
				{
					this.OnExciseNumberChanging(value);
					this.SendPropertyChanging();
					this._ExciseNumber = value;
					this.SendPropertyChanged("ExciseNumber");
					this.OnExciseNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PFESINumber", DbType="NVarChar(50)")]
		public string PFESINumber
		{
			get
			{
				return this._PFESINumber;
			}
			set
			{
				if ((this._PFESINumber != value))
				{
					this.OnPFESINumberChanging(value);
					this.SendPropertyChanging();
					this._PFESINumber = value;
					this.SendPropertyChanged("PFESINumber");
					this.OnPFESINumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BusinessGUID
		{
			get
			{
				return this._BusinessGUID;
			}
			set
			{
				if ((this._BusinessGUID != value))
				{
					if (this._PersonalInformation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBusinessGUIDChanging(value);
					this.SendPropertyChanging();
					this._BusinessGUID = value;
					this.SendPropertyChanged("BusinessGUID");
					this.OnBusinessGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonalInformation_OtherInfo", Storage="_PersonalInformation", ThisKey="BusinessGUID", OtherKey="BusinessGUID", IsForeignKey=true)]
		public PersonalInformation PersonalInformation
		{
			get
			{
				return this._PersonalInformation.Entity;
			}
			set
			{
				PersonalInformation previousValue = this._PersonalInformation.Entity;
				if (((previousValue != value) 
							|| (this._PersonalInformation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PersonalInformation.Entity = null;
						previousValue.OtherInfos.Remove(this);
					}
					this._PersonalInformation.Entity = value;
					if ((value != null))
					{
						value.OtherInfos.Add(this);
						this._BusinessGUID = value.BusinessGUID;
					}
					else
					{
						this._BusinessGUID = default(string);
					}
					this.SendPropertyChanged("PersonalInformation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
