//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.AdminServicesNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServicesNS.IAdminServices")]
    public interface IAdminServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServices/addNewRole", ReplyAction="http://tempuri.org/IAdminServices/addNewRoleResponse")]
        bool addNewRole(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServices/addNewRole", ReplyAction="http://tempuri.org/IAdminServices/addNewRoleResponse")]
        System.Threading.Tasks.Task<bool> addNewRoleAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServices/addNewUser", ReplyAction="http://tempuri.org/IAdminServices/addNewUserResponse")]
        bool addNewUser(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServices/addNewUser", ReplyAction="http://tempuri.org/IAdminServices/addNewUserResponse")]
        System.Threading.Tasks.Task<bool> addNewUserAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServicesChannel : MDK.AdminServicesNS.IAdminServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServicesClient : System.ServiceModel.ClientBase<MDK.AdminServicesNS.IAdminServices>, MDK.AdminServicesNS.IAdminServices {
        
        public AdminServicesClient() {
        }
        
        public AdminServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addNewRole(string data) {
            return base.Channel.addNewRole(data);
        }
        
        public System.Threading.Tasks.Task<bool> addNewRoleAsync(string data) {
            return base.Channel.addNewRoleAsync(data);
        }
        
        public bool addNewUser(string data) {
            return base.Channel.addNewUser(data);
        }
        
        public System.Threading.Tasks.Task<bool> addNewUserAsync(string data) {
            return base.Channel.addNewUserAsync(data);
        }
    }
}
